services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  orchestrator:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: orchestrator
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - redis

#  frame-extractor:
#    build:
#      context: ./frame-extractor-service
#    container_name: frame-extractor
#    ports:
#      - "8082:8082"
#    depends_on:
#      - rabbitmq
#
#  auth:
#    build:
#      context: ./auth
#    container_name: auth
#    ports:
#      - "8080:8080"
#
#  frontend:
#    build:
#      context: ./hackaton-ui
#    container_name: frontend
#    ports:
#      - "4200:4200"